package luvnhi.luvbap.local.preferences

object PreferencesKey {
    const val COUNTRY_CODE = "COUNTRY_CODE"
    const val URL_WALLPAPER_LIVE_IF_PREVIEW = "URL_WALLPAPER_LIVE_IF_PREVIEW"
    const val URL_WALLPAPER_LIVE_IF_SET = "URL_WALLPAPER_LIVE_IF_SET"
    const val IS_FIRST_TIME_OPEN_APP = "IS_FIRST_TIME_OPEN_APP"
    const val IS_SHOW_TUTORIAL_FAVOUR_PICTURE = "IS_SHOW_TUTORIAL_FAVOUR_PICTURE"

    const val IS_ENABLE_DARK_MODE = "IS_ENABLE_DARK_MODE"



    const val IS_VIBRATION_COLORING = "IS_VIBRATION_COLORING"
}
